// 100 Unique Pakistani Customer Names (Male and Female)
export const PAKISTANI_NAMES = [
  "Muhammad Ali", "Fatima Khan", "Usman Ahmed", "Ayesha Malik", "Bilal Hassan",
  "Sana Sheikh", "Hamza Raza", "Zainab Bibi", "Omer Farooq", "Mariam Nawaz",
  "Zubair Shah", "Hira Tariq", "Taha Siddiqui", "Anum Rasheed", "Saad Abbasi",
  "Sadia Iqbal", "Fahad Qureshi", "Khadija Mahmood", "Shahzaib Butt", "Mahnoor Zafar",
  "Asad Ullah", "Nimra Chaudhry", "Danyal Aziz", "Rabia Javed", "Waqas Yousaf",
  "Laiba Ashraf", "Adeel Mirza", "Kinza Hashmi", "Nabeel Rehman", "Iqra Saeed",
  "Waqar Ahmad", "Saman Shahzadi", "Daniyal Ali", "Saba Naz", "Haris Mehmood",
  "Hafsa Noor", "Ahsan Raza", "Bushra Bibi", "Faisal Javed", "Mehak Fatima",
  "Zeeshan Akram", "Sumaira Parveen", "Imran Khan", "Sidra Tul Muntaha", "Kamran Hussain",
  "Mona Malik", "Shoaib Akhtar", "Rida Zahra", "Kashif Mahmood", "Amna Sheikh",
  "Noman Tariq", "Fareeha Gul", "Sami Ur Rehman", "Kiran Shahzadi", "Rehan Mansoor",
  "Tooba Akhtar", "Atif Aslam", "Yashfeen Ahmed", "Shehryar Munawar", "Bisma Maroof",
  "Talha Anjum", "Alishba Khan", "Mubeen Ahmed", "Areeba Siddiqui", "Sameer Butt",
  "Maria B", "Zohaib Hassan", "Eman Fatima", "Sharjeel Khan", "Tehreem Zafar",
  "Arslan Ash", "Minahil Abid", "Sufyan Ali", "Maheen Chaudhry", "Junaid Jamshed",
  "Syeda Fatima", "Muneeb Butt", "Hania Amir", "Shahid Afridi", "Natasha Ali",
  "Fawad Khan", "Zoya Hassan", "Faris Shafi", "Rimsha Noor", "Ali Zafar",
  "Rumaisa Khan", "Mustafa Zahid", "Ushna Shah", "Shayan Ahmed", "Aima Baig",
  "Azhar Ali", "Sarah Khan", "Babar Azam", "Dua Malik", "Naseem Shah",
  "Iqra Aziz", "Shaheen Afridi", "Kinza Hashmi", "Haris Rauf", "Sajal Ali"
];

// 100 Unique Reviews (75% Roman Urdu, 18% Urdu Unicode, 7% English)
// Ratings range 4-5 stars naturally.
export const REVIEW_DATASET = [
  // Roman Urdu (75)
  { text: "Bhut achi quality hai, jesa dekha tha bilkul wesa hi mila.", rating: 5 },
  { text: "Packing boht zabardast thi. Fast delivery!", rating: 5 },
  { text: "Boht pyari cheez hai, 100% recommended 👍", rating: 5 },
  { text: "Price ke hisab se buhat behtar hai.", rating: 4 },
  { text: "Quality impressive hai. Dil khush ho gaya.", rating: 5 },
  { text: "Delivery time thora late tha lekin product zabardast hai.", rating: 4 },
  { text: "Acha stuff hai, highly recommended!", rating: 5 },
  { text: "Bht zabardast hai, dobara order karunga zaroor.", rating: 5 },
  { text: "Bilkul original item mila hai. Thanks seller!", rating: 5 },
  { text: "Quality bohat achi hai. Very satisfied 🔥", rating: 5 },
  { text: "Shuru me thora doubt tha lekin received hone k baad khushi hui.", rating: 4 },
  { text: "Zabardast product. 5 stars from my side ✨", rating: 5 },
  { text: "Paisa vasool cheez hai bhaiya!", rating: 5 },
  { text: "Quality behtareen hai aur kapra bhi soft hai.", rating: 5 },
  { text: "Maza aa gaya product dekh kar.", rating: 5 },
  { text: "Achi hai bas color thora dark hai picture se.", rating: 4 },
  { text: "Mashallah boht hi umdah quality hai.", rating: 5 },
  { text: "Super fast delivery, 2 din me mil gaya.", rating: 5 },
  { text: "Vekhne me zabardast, use me bhi awesome.", rating: 5 },
  { text: "Recommended seller! Bohot imandari se kaam kar rahy hain.", rating: 5 },
  { text: "Bhai maza agaya, boht pyari cheez hai.", rating: 5 },
  { text: "Packing achi thi product safe pohncha.", rating: 4 },
  { text: "Satisfied with the purchase. Pure quality 👌", rating: 5 },
  { text: "Thora sa size ka issue tha baqi sab perfect hai.", rating: 4 },
  { text: "Acha hai lekin price thori kam honi chahiye thi.", rating: 4 },
  { text: "Boht acha hai, family ko bhi boht pasand aya.", rating: 5 },
  { text: "Outclass quality! Ek number cheez.", rating: 5 },
  { text: "Bhai kamaal kar diya aap ne. Best store!", rating: 5 },
  { text: "Bhut pyara hai, color bilkul exact wohi hai.", rating: 5 },
  { text: "Everything is super fine.", rating: 4 },
  { text: "Delivery boy ka bht acha behave tha, product b 10/10 hai.", rating: 5 },
  { text: "Mujhe boht pasand aya. Shukriya!", rating: 5 },
  { text: "Quality achi hai, bilkul jesa pic me tha.", rating: 5 },
  { text: "Overall acha experience raha turabi k sath.", rating: 4 },
  { text: "Bohot zabardast aur durable lag raha hai.", rating: 5 },
  { text: "Very nice product, worth every rupee.", rating: 5 },
  { text: "Nice packaging, fast delivery. Fully satisfied 🎉", rating: 5 },
  { text: "Bhut khoob! 100% genuine.", rating: 5 },
  { text: "Boht umdah finish hai.", rating: 5 },
  { text: "Bhai sahab kamaal stuff hai 💯", rating: 5 },
  { text: "MashaAllah boht behtareen. Highly recommended store.", rating: 5 },
  { text: "Acha experience tha, 4 stars de raha hu.", rating: 4 },
  { text: "Zabardast yaar, expected se ziada acha nikla.", rating: 5 },
  { text: "Nice item, good seller communication.", rating: 4 },
  { text: "Bilkul perfect size aur fitting hai.", rating: 5 },
  { text: "Quality to outclass hai sir!", rating: 5 },
  { text: "Bohot achi purchase rahi meri. Thanks!", rating: 5 },
  { text: "Product ekdum top quality hai.", rating: 5 },
  { text: "Kam Daam me Behtareen Cheez.", rating: 5 },
  { text: "Acha hai, use kar ke maza aya.", rating: 4 },
  { text: "Acha product hai, koi issue nahi aya.", rating: 5 },
  { text: "Superb quality & fast shipping ✨", rating: 5 },
  { text: "Packaging ko thora improve karein baqi product fit hai.", rating: 4 },
  { text: "Bohot hi shandaar cheez bani hai.", rating: 5 },
  { text: "Very happy customer. Phir order karunga.", rating: 5 },
  { text: "Quality 10/10, service 10/10.", rating: 5 },
  { text: "Boht cute hai aur kaam bhi zabardast karta hai.", rating: 5 },
  { text: "Price justified hai quality k sath.", rating: 4 },
  { text: "Zabardast product hai, bhai ne recommend kiya tha.", rating: 5 },
  { text: "Sachi me boht achi quality hai.", rating: 5 },
  { text: "Nice product. Recommended to all.", rating: 4 },
  { text: "Acha laga dekh ke, packing b original thi.", rating: 5 },
  { text: "Bhut pyara material hai soft and comfortable.", rating: 5 },
  { text: "Fast shipping in Lahore! Parcel received in 24 hours.", rating: 5 },
  { text: "Nice product, money worth it.", rating: 4 },
  { text: "Muje to boht hi pasand aya hai.", rating: 5 },
  { text: "Acha experience raha, no complaints.", rating: 4 },
  { text: "Bilkul mind blowing quality 🔥", rating: 5 },
  { text: "Boht behtar response aur fast courier.", rating: 5 },
  { text: "Sahi cheez bheji hai seller ne.", rating: 5 },
  { text: "Bohot zabardast, 5 stars ⭐️⭐️⭐️⭐️⭐️", rating: 5 },
  { text: "Ek dum mast item hai bhai.", rating: 5 },
  { text: "Finishing aur detail boht achi hai.", rating: 5 },
  { text: "Pehli baar buy kiya tha par boht acha experience raha.", rating: 4 },
  { text: "Great quality product, thanks Turabi!", rating: 5 },

  // Urdu Unicode (18)
  { text: "ماشاءاللہ بہت ہی عمدہ کوالٹی ہے۔ دل خوش ہو گیا۔", rating: 5 },
  { text: "بہت زبردست پروڈکٹ ہے۔ بالکل جیسا دکھایا ویسا ہی ملا۔", rating: 5 },
  { text: "کمال کی چیز ہے، قیمت کے حساب سے بہترین۔", rating: 5 },
  { text: "پیکنگ بہت اچھی تھی اور ڈیلیوری بھی وقت پر ہوئی۔", rating: 5 },
  { text: "بہت ہی پیاری چیز ہے۔ 100% ریکمینڈڈ!", rating: 5 },
  { text: "کوالٹی زبردست ہے، دوبارہ بھی آرڈر کروں گا۔", rating: 5 },
  { text: "بہت اچھا تجربہ رہا، شکریہ سيلر۔", rating: 4 },
  { text: "بالکل اوریجنل اور بہترین کوالٹی۔", rating: 5 },
  { text: "بہت مرید اور فائدے مند پروڈکٹ ہے۔", rating: 5 },
  { text: "پیسہ وصول چیز ہے، ماشاءاللہ۔", rating: 5 },
  { text: "کوالٹی اچھی ہے لیکن ڈیلیوری ایک دن لیٹ تھی۔", rating: 4 },
  { text: "بہت عمدہ فائنل فنشنگ ہے۔", rating: 5 },
  { text: "زبردست چیز ہے، ہر کسی کو لینی چاہیے۔", rating: 5 },
  { text: "خرید کر خوشی ہوئی، معیار 10/10 ہے۔", rating: 5 },
  { text: "بہت پیارا کپڑا اور فنشنگ ہے، شکریہ!", rating: 5 },
  { text: "بہت زبردست سروس اور فاسٹ ڈیلیوری۔", rating: 5 },
  { text: "مجموعی طور پر بہت اچھا پروڈکٹ ہے۔", rating: 4 },
  { text: "بہت اعلیٰ معیار، ماشاءاللہ۔", rating: 5 },

  // English (7)
  { text: "Extremely satisfied with the product quality and packaging!", rating: 5 },
  { text: "Fast delivery and great customer service. Will buy again.", rating: 5 },
  { text: "Worth buying! Material feels premium.", rating: 5 },
  { text: "Good product, minor delay in shipping but overall 4 stars.", rating: 4 },
  { text: "Excellent quality. Exactly as described.", rating: 5 },
  { text: "Nice packaging and prompt delivery. Highly recommended!", rating: 5 },
  { text: "Very good experience. Product quality is top notch.", rating: 5 }
];
